### ISSUE TITLE
Duplicate Symbols when building Xamarin.Forms solution

### ISSUE THREAD

**Issue by ivanleapfactor** [BlinkID/blinkid-xamarin#10] opened 2017-06-23 20:23 UTC
MTOUCH: error MT5209: Native linking error: warning: object file (/Users/.../BlinkID.a(BlinkID-i386-master.o)) was built for newer iOS version (9.2) than being linked (9.0)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPApp'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPAusIDBackRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPAusIDBackRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPAusIDFrontRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPAusIDFrontRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBarDecoderRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBarDecoderRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBarcodeDetailedData'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBarcodeElement'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBarcodeOverlayViewController'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBaseBarcodeOverlayViewController'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBaseOverlayViewController'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBasePhotoPayOverlayViewController'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBlinkOcrRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBlinkOcrRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPBlurredFieldOfViewOverlaySubview'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCameraCoordinator'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCameraSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCoordinator'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCroIDBackRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCroIDBackRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCroIDFrontRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCroIDFrontRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCzIDBackRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCzIDBackRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCzIDFrontRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPCzIDFrontRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDateOcrParserFactory'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDecodingInfo'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDetectorRecognizerResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDetectorRecognizerSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDetectorResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDetectorSettings'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5212: Native linking failed, duplicate symbol: '_OBJC_CLASS_$_PPDocumentDetectorResult'.
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../BlinkID.a(BlinkID-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5213: Duplicate symbol in: /Users/.../MicroBlink.framework/MicroBlink(MicroBlink-i386-master.o) (Location related to previous error)
	MTOUCH: error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker 

even the Samples/Forms/Forms.sln shows the same errors when linking

any clues would be appreciated!
Ivan.

**Comment by stepanic** [comment] 2017-06-30 15:19
@ivanleapfactor we are not able to reproduce this kind of error and right now we made a successfully runnable application from a fresh clone of the repository.
Now I will close this issue.

**Comment by ivanleapfactor** [comment] 2017-06-30 15:20
Can you send me your project?

**Closed by stepanic** 2017-06-30 15:19 UTC

**Comment by ivanleapfactor** [comment] 2017-06-30 15:21
Can you send me your new project?

**Comment by stepanic** [comment] 2017-06-30 15:25
@ivanleapfactor just clone the current state of `master` this will be released ASAP as v1.0

I will additionally send you ZIP file with the whole working application from my computer, with all binary compiled files inside.
